spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ec50n9
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

blog:
  title: ec50n9 的小世界
  banner:
    title: 警告
    content: 博客明天就会关闭