POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "ec50n9",
  "password": "1234"
}

### 登录测试
GET localhost:8080/api/auth/test
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYzUwbjkiLCJleHAiOjE2NzM4ODA3NjZ9.0612bH33znzG-S0Lnjldj6nhtMN10ELogcAjHQoGU44
