POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "ec50n9",
  "password": "1234"
}

> {%
    client.global.set("auth_token", response.body.data);
%}

### 登录测试
GET localhost:8080/api/auth/test
token: {{auth_token}}

### 退出登录
POST localhost:8080/api/auth/logout
token: {{auth_token}}

### 用户列表
GET localhost:8080/api/users

### 单个用户
GET localhost:8080/api/users/sugar

### 创建用户
POST localhost:8080/api/users
Content-Type: application/json

{
  "username": "sugar",
  "password": "1234",
  "firstname": "Yanqiong",
  "lastname": "Tan"
}

### 更新用户
PUT localhost:8080/api/users/1
Content-Type: application/json

{
  "username": "shello",
  "password": "6666",
  "firstname": "gogo",
  "lastname": "let"
}

### 补丁更新用户
PATCH localhost:8080/api/users/1
Content-Type: application/json

{
  "username": "ec50n9",
  "description": "你好，世界"
}

### 删除用户
DELETE localhost:8080/api/users/4

### 文章列表
GET localhost:8080/api/articles

### 单个文章
GET localhost:8080/api/articles/reactor-aluminium-has-landed

### 创建文章
POST localhost:8080/api/articles
Content-Type: application/json

{
  "title": "ec50n9 is handsome",
  "headline": "this is headline",
  "content": "哈哈哈，今天天气真不错",
  "authorId": 1
}

### 更新文章
PUT localhost:8080/api/articles/4
Content-Type: application/json

{
  "title": "哈哈哈",
  "headline": "this is headline",
  "content": "哈哈哈，今天天气真不错",
  "authorId": 1,
  "slug": "hello"
}

### 补丁更新文章
PATCH localhost:8080/api/articles/4
Content-Type: application/json

{
  "slug": "gogogo"
}

### 删除文章
DELETE localhost:8080/api/articles/3
token: {{auth_token}}
